---
- name: Odroid maitenance tasks
  hosts: odroid
  become: true
  tasks:
    - name: Upgrade packages
      ansible.builtin.apt:
        name: "*"
        update_cache: true
        force_apt_get: true
        state: latest
