---
- name: Install/upgrade required Apt packages
  become: true
  ansible.builtin.apt:
    name: "python3-pip"
    update_cache: true
    force_apt_get: true
    state: latest

- name: Install requirements for Ansible to use docker
  ansible.builtin.pip:
    name: docker
